package com.myspace.sdm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PhysicalAbuse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean suspiciousDeath;
	private java.lang.Boolean nonAccidentalInjury;
	private java.lang.Boolean injuryInconsistent;

	private java.lang.String result;

	public PhysicalAbuse() {
	}

	public java.lang.Boolean getSuspiciousDeath() {
		return this.suspiciousDeath;
	}

	public void setSuspiciousDeath(java.lang.Boolean suspiciousDeath) {
		this.suspiciousDeath = suspiciousDeath;
	}

	public java.lang.Boolean getNonAccidentalInjury() {
		return this.nonAccidentalInjury;
	}

	public void setNonAccidentalInjury(java.lang.Boolean nonAccidentalInjury) {
		this.nonAccidentalInjury = nonAccidentalInjury;
	}

	public java.lang.Boolean getInjuryInconsistent() {
		return this.injuryInconsistent;
	}

	public void setInjuryInconsistent(java.lang.Boolean injuryInconsistent) {
		this.injuryInconsistent = injuryInconsistent;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public PhysicalAbuse(java.lang.Boolean suspiciousDeath,
			java.lang.Boolean nonAccidentalInjury,
			java.lang.Boolean injuryInconsistent, java.lang.String result) {
		this.suspiciousDeath = suspiciousDeath;
		this.nonAccidentalInjury = nonAccidentalInjury;
		this.injuryInconsistent = injuryInconsistent;
		this.result = result;
	}

}